# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gosweeper < Formula
  desc "Play minesweeper in your terminal"
  homepage "https://github.com/dferramosi/gosweeper"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dferramosi/gosweeper/releases/download/v0.0.1/gosweeper_0.0.1_darwin_amd64.tar.gz"
      sha256 "a9848a7e66fd315a07ec8a82e6fdc6704c22dfb073a710ec2a0cd4ada265ef3c"

      def install
        bin.install "gosweeper" => "gosweeper"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dferramosi/gosweeper/releases/download/v0.0.1/gosweeper_0.0.1_darwin_arm64.tar.gz"
      sha256 "47372ec5b3c6a83447540b13cbbb8d72dc51e1fce2658558d24449b57011500c"

      def install
        bin.install "gosweeper" => "gosweeper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dferramosi/gosweeper/releases/download/v0.0.1/gosweeper_0.0.1_linux_amd64.tar.gz"
        sha256 "b4053bf251f203bf1615414a4e68c21f68135f1080c297996fca8c722d8ad54d"

        def install
          bin.install "gosweeper" => "gosweeper"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dferramosi/gosweeper/releases/download/v0.0.1/gosweeper_0.0.1_linux_arm64.tar.gz"
        sha256 "51d90c3145cf89ec18f2496712166c6afd667e699a6a7aceffcfac73dce42d74"

        def install
          bin.install "gosweeper" => "gosweeper"
        end
      end
    end
  end
end
