# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gosweeper < Formula
  desc "Play minesweeper in your terminal"
  homepage "https://github.com/dferramosi/gosweeper"
  version "0.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dferramosi/gosweeper/releases/download/v0.0.0/gosweeper_0.0.0_darwin_amd64.tar.gz"
      sha256 "19ba194edae71ecc1cb15ee7217d1b3c7bd7d82ce715f9dd55b4773eb6a9227c"

      def install
        bin.install "gosweeper" => "gosweeper"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dferramosi/gosweeper/releases/download/v0.0.0/gosweeper_0.0.0_darwin_arm64.tar.gz"
      sha256 "a80b50fa7493110bdae24507421ce3c99410035307e242314dde3a8f4d473a47"

      def install
        bin.install "gosweeper" => "gosweeper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dferramosi/gosweeper/releases/download/v0.0.0/gosweeper_0.0.0_linux_amd64.tar.gz"
        sha256 "3136bf572d5e2b79dd60db0dc41f1d0f1e846076c668362b092da1c456e66fca"

        def install
          bin.install "gosweeper" => "gosweeper"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dferramosi/gosweeper/releases/download/v0.0.0/gosweeper_0.0.0_linux_arm64.tar.gz"
        sha256 "10b61f0622d4ddab11d2a960811f00f3174312b26a21730c5925e8b3686a4ff9"

        def install
          bin.install "gosweeper" => "gosweeper"
        end
      end
    end
  end
end
