# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gosweeper < Formula
  desc "Play minesweeper in your terminal"
  homepage "https://github.com/dferramosi/gosweeper"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dferramosi/gosweeper/releases/download/v0.0.2/gosweeper_0.0.2_darwin_amd64.tar.gz"
      sha256 "877ef01c39ff16e5bec83bb790860834beb6aa625ae58224b9872701792345d5"

      def install
        bin.install "gosweeper" => "gosweeper"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dferramosi/gosweeper/releases/download/v0.0.2/gosweeper_0.0.2_darwin_arm64.tar.gz"
      sha256 "6e07a3fee4966db8d28c341021904f4ef76f3f99134381f147cbea37c7c307b3"

      def install
        bin.install "gosweeper" => "gosweeper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dferramosi/gosweeper/releases/download/v0.0.2/gosweeper_0.0.2_linux_amd64.tar.gz"
        sha256 "88c463546adeb750b8b65fc7249f279fc49fa59ab60da35c442bbf74bdfc5cc5"

        def install
          bin.install "gosweeper" => "gosweeper"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dferramosi/gosweeper/releases/download/v0.0.2/gosweeper_0.0.2_linux_arm64.tar.gz"
        sha256 "e91854368eb380d6eff36b3f070998e3461e4911925b39f4f7fc66f9efd2a090"

        def install
          bin.install "gosweeper" => "gosweeper"
        end
      end
    end
  end
end
